//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.02 at 05:47:07 PM MST 
//


package com.hsphoenix.csg.sodi.provisionable.order;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.hsphoenix.csg.sodi.BusinessKey;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Business" type="{}businessKey"/>
 *         &lt;element name="Customer">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}CustomerId"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Location">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}LocationId"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Order">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}OrderId"/>
 *                   &lt;element ref="{}Class"/>
 *                   &lt;element ref="{}Status"/>
 *                   &lt;element ref="{}Version"/>
 *                   &lt;element ref="{}DueDate" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ItemList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Item" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}ServiceIdentifier"/>
 *                             &lt;element ref="{}AccountId"/>
 *                             &lt;element ref="{}ParentServiceIdentifier"/>
 *                             &lt;choice minOccurs="0">
 *                               &lt;element ref="{}TelephoneNumberId"/>
 *                               &lt;element ref="{}CallingCardId"/>
 *                               &lt;element ref="{}UserDefinedIdentifier"/>
 *                             &lt;/choice>
 *                             &lt;element name="TelephoneNumberBlock" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}StartTelephoneNumberId"/>
 *                                       &lt;element ref="{}EndTelephoneNumberId"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element ref="{}HierarchyLevel" minOccurs="0"/>
 *                             &lt;element ref="{}Status"/>
 *                             &lt;element ref="{}ProvisioningCode"/>
 *                             &lt;element ref="{}ProvisioningCodeDescription" minOccurs="0"/>
 *                             &lt;element name="CustomField" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element ref="{}Value"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="Index" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TelephoneNumberList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TelephoneNumber" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}TelephoneNumberId"/>
 *                             &lt;element ref="{}Native"/>
 *                             &lt;element ref="{}PortedType"/>
 *                             &lt;element ref="{}Switch" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CallingCardList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CallingCard" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}CallingCardId"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TelephoneNumberBlockList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TelephoneNumberBlock" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}StartTelephoneNumberId"/>
 *                             &lt;element ref="{}EndTelephoneNumberId"/>
 *                             &lt;element ref="{}Native"/>
 *                             &lt;element ref="{}PortedType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "business",
    "customer",
    "location",
    "order",
    "itemList",
    "telephoneNumberList",
    "callingCardList",
    "telephoneNumberBlockList"
})
@XmlRootElement(name = "ProvisionableOrderCompleted")
public class ProvisionableOrderCompleted {

    @XmlElement(name = "Business", required = true)
    protected BusinessKey business;
    @XmlElement(name = "Customer", required = true)
    protected ProvisionableOrderCompleted.Customer customer;
    @XmlElement(name = "Location", required = true)
    protected ProvisionableOrderCompleted.Location location;
    @XmlElement(name = "Order", required = true)
    protected ProvisionableOrderCompleted.Order order;
    @XmlElement(name = "ItemList")
    protected ProvisionableOrderCompleted.ItemList itemList;
    @XmlElement(name = "TelephoneNumberList")
    protected ProvisionableOrderCompleted.TelephoneNumberList telephoneNumberList;
    @XmlElement(name = "CallingCardList")
    protected ProvisionableOrderCompleted.CallingCardList callingCardList;
    @XmlElement(name = "TelephoneNumberBlockList")
    protected ProvisionableOrderCompleted.TelephoneNumberBlockList telephoneNumberBlockList;

    /**
     * Gets the value of the business property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessKey }
     *     
     */
    public BusinessKey getBusiness() {
        return business;
    }

    /**
     * Sets the value of the business property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessKey }
     *     
     */
    public void setBusiness(BusinessKey value) {
        this.business = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionableOrderCompleted.Customer }
     *     
     */
    public ProvisionableOrderCompleted.Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionableOrderCompleted.Customer }
     *     
     */
    public void setCustomer(ProvisionableOrderCompleted.Customer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionableOrderCompleted.Location }
     *     
     */
    public ProvisionableOrderCompleted.Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionableOrderCompleted.Location }
     *     
     */
    public void setLocation(ProvisionableOrderCompleted.Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionableOrderCompleted.Order }
     *     
     */
    public ProvisionableOrderCompleted.Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionableOrderCompleted.Order }
     *     
     */
    public void setOrder(ProvisionableOrderCompleted.Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the itemList property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionableOrderCompleted.ItemList }
     *     
     */
    public ProvisionableOrderCompleted.ItemList getItemList() {
        return itemList;
    }

    /**
     * Sets the value of the itemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionableOrderCompleted.ItemList }
     *     
     */
    public void setItemList(ProvisionableOrderCompleted.ItemList value) {
        this.itemList = value;
    }

    /**
     * Gets the value of the telephoneNumberList property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionableOrderCompleted.TelephoneNumberList }
     *     
     */
    public ProvisionableOrderCompleted.TelephoneNumberList getTelephoneNumberList() {
        return telephoneNumberList;
    }

    /**
     * Sets the value of the telephoneNumberList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionableOrderCompleted.TelephoneNumberList }
     *     
     */
    public void setTelephoneNumberList(ProvisionableOrderCompleted.TelephoneNumberList value) {
        this.telephoneNumberList = value;
    }

    /**
     * Gets the value of the callingCardList property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionableOrderCompleted.CallingCardList }
     *     
     */
    public ProvisionableOrderCompleted.CallingCardList getCallingCardList() {
        return callingCardList;
    }

    /**
     * Sets the value of the callingCardList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionableOrderCompleted.CallingCardList }
     *     
     */
    public void setCallingCardList(ProvisionableOrderCompleted.CallingCardList value) {
        this.callingCardList = value;
    }

    /**
     * Gets the value of the telephoneNumberBlockList property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisionableOrderCompleted.TelephoneNumberBlockList }
     *     
     */
    public ProvisionableOrderCompleted.TelephoneNumberBlockList getTelephoneNumberBlockList() {
        return telephoneNumberBlockList;
    }

    /**
     * Sets the value of the telephoneNumberBlockList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisionableOrderCompleted.TelephoneNumberBlockList }
     *     
     */
    public void setTelephoneNumberBlockList(ProvisionableOrderCompleted.TelephoneNumberBlockList value) {
        this.telephoneNumberBlockList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CallingCard" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}CallingCardId"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "callingCard"
    })
    public static class CallingCardList {

        @XmlElement(name = "CallingCard", required = true)
        protected List<ProvisionableOrderCompleted.CallingCardList.CallingCard> callingCard;

        /**
         * Gets the value of the callingCard property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the callingCard property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCallingCard().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProvisionableOrderCompleted.CallingCardList.CallingCard }
         * 
         * 
         */
        public List<ProvisionableOrderCompleted.CallingCardList.CallingCard> getCallingCard() {
            if (callingCard == null) {
                callingCard = new ArrayList<ProvisionableOrderCompleted.CallingCardList.CallingCard>();
            }
            return this.callingCard;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}CallingCardId"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "callingCardId"
        })
        public static class CallingCard {

            @XmlElement(name = "CallingCardId", required = true)
            protected String callingCardId;

            /**
             * Gets the value of the callingCardId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCallingCardId() {
                return callingCardId;
            }

            /**
             * Sets the value of the callingCardId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCallingCardId(String value) {
                this.callingCardId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}CustomerId"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customerId"
    })
    public static class Customer {

        @XmlElement(name = "CustomerId", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger customerId;

        /**
         * Gets the value of the customerId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCustomerId() {
            return customerId;
        }

        /**
         * Sets the value of the customerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCustomerId(BigInteger value) {
            this.customerId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Item" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}ServiceIdentifier"/>
     *                   &lt;element ref="{}AccountId"/>
     *                   &lt;element ref="{}ParentServiceIdentifier"/>
     *                   &lt;choice minOccurs="0">
     *                     &lt;element ref="{}TelephoneNumberId"/>
     *                     &lt;element ref="{}CallingCardId"/>
     *                     &lt;element ref="{}UserDefinedIdentifier"/>
     *                   &lt;/choice>
     *                   &lt;element name="TelephoneNumberBlock" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}StartTelephoneNumberId"/>
     *                             &lt;element ref="{}EndTelephoneNumberId"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element ref="{}HierarchyLevel" minOccurs="0"/>
     *                   &lt;element ref="{}Status"/>
     *                   &lt;element ref="{}ProvisioningCode"/>
     *                   &lt;element ref="{}ProvisioningCodeDescription" minOccurs="0"/>
     *                   &lt;element name="CustomField" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element ref="{}Value"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="Index" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class ItemList {

        @XmlElement(name = "Item", required = true)
        protected List<ProvisionableOrderCompleted.ItemList.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProvisionableOrderCompleted.ItemList.Item }
         * 
         * 
         */
        public List<ProvisionableOrderCompleted.ItemList.Item> getItem() {
            if (item == null) {
                item = new ArrayList<ProvisionableOrderCompleted.ItemList.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}ServiceIdentifier"/>
         *         &lt;element ref="{}AccountId"/>
         *         &lt;element ref="{}ParentServiceIdentifier"/>
         *         &lt;choice minOccurs="0">
         *           &lt;element ref="{}TelephoneNumberId"/>
         *           &lt;element ref="{}CallingCardId"/>
         *           &lt;element ref="{}UserDefinedIdentifier"/>
         *         &lt;/choice>
         *         &lt;element name="TelephoneNumberBlock" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}StartTelephoneNumberId"/>
         *                   &lt;element ref="{}EndTelephoneNumberId"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element ref="{}HierarchyLevel" minOccurs="0"/>
         *         &lt;element ref="{}Status"/>
         *         &lt;element ref="{}ProvisioningCode"/>
         *         &lt;element ref="{}ProvisioningCodeDescription" minOccurs="0"/>
         *         &lt;element name="CustomField" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element ref="{}Value"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="Index" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "serviceIdentifier",
            "accountId",
            "parentServiceIdentifier",
            "telephoneNumberId",
            "callingCardId",
            "userDefinedIdentifier",
            "telephoneNumberBlock",
            "hierarchyLevel",
            "status",
            "provisioningCode",
            "provisioningCodeDescription",
            "customField"
        })
        public static class Item {

            @XmlElement(name = "ServiceIdentifier", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger serviceIdentifier;
            @XmlElement(name = "AccountId", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger accountId;
            @XmlElement(name = "ParentServiceIdentifier", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger parentServiceIdentifier;
            @XmlElement(name = "TelephoneNumberId")
            protected String telephoneNumberId;
            @XmlElement(name = "CallingCardId")
            protected String callingCardId;
            @XmlElement(name = "UserDefinedIdentifier")
            protected String userDefinedIdentifier;
            @XmlElement(name = "TelephoneNumberBlock")
            protected List<ProvisionableOrderCompleted.ItemList.Item.TelephoneNumberBlock> telephoneNumberBlock;
            @XmlElement(name = "HierarchyLevel")
            protected String hierarchyLevel;
            @XmlElement(name = "Status", required = true)
            protected String status;
            @XmlElement(name = "ProvisioningCode", required = true)
            protected String provisioningCode;
            @XmlElement(name = "ProvisioningCodeDescription")
            protected String provisioningCodeDescription;
            @XmlElement(name = "CustomField")
            protected List<ProvisionableOrderCompleted.ItemList.Item.CustomField> customField;

            /**
             * Gets the value of the serviceIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getServiceIdentifier() {
                return serviceIdentifier;
            }

            /**
             * Sets the value of the serviceIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setServiceIdentifier(BigInteger value) {
                this.serviceIdentifier = value;
            }

            /**
             * Gets the value of the accountId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAccountId() {
                return accountId;
            }

            /**
             * Sets the value of the accountId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAccountId(BigInteger value) {
                this.accountId = value;
            }

            /**
             * Gets the value of the parentServiceIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getParentServiceIdentifier() {
                return parentServiceIdentifier;
            }

            /**
             * Sets the value of the parentServiceIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setParentServiceIdentifier(BigInteger value) {
                this.parentServiceIdentifier = value;
            }

            /**
             * Gets the value of the telephoneNumberId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTelephoneNumberId() {
                return telephoneNumberId;
            }

            /**
             * Sets the value of the telephoneNumberId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTelephoneNumberId(String value) {
                this.telephoneNumberId = value;
            }

            /**
             * Gets the value of the callingCardId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCallingCardId() {
                return callingCardId;
            }

            /**
             * Sets the value of the callingCardId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCallingCardId(String value) {
                this.callingCardId = value;
            }

            /**
             * Gets the value of the userDefinedIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserDefinedIdentifier() {
                return userDefinedIdentifier;
            }

            /**
             * Sets the value of the userDefinedIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserDefinedIdentifier(String value) {
                this.userDefinedIdentifier = value;
            }

            /**
             * Gets the value of the telephoneNumberBlock property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the telephoneNumberBlock property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTelephoneNumberBlock().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ProvisionableOrderCompleted.ItemList.Item.TelephoneNumberBlock }
             * 
             * 
             */
            public List<ProvisionableOrderCompleted.ItemList.Item.TelephoneNumberBlock> getTelephoneNumberBlock() {
                if (telephoneNumberBlock == null) {
                    telephoneNumberBlock = new ArrayList<ProvisionableOrderCompleted.ItemList.Item.TelephoneNumberBlock>();
                }
                return this.telephoneNumberBlock;
            }

            /**
             * Gets the value of the hierarchyLevel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHierarchyLevel() {
                return hierarchyLevel;
            }

            /**
             * Sets the value of the hierarchyLevel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHierarchyLevel(String value) {
                this.hierarchyLevel = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the provisioningCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProvisioningCode() {
                return provisioningCode;
            }

            /**
             * Sets the value of the provisioningCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProvisioningCode(String value) {
                this.provisioningCode = value;
            }

            /**
             * Gets the value of the provisioningCodeDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProvisioningCodeDescription() {
                return provisioningCodeDescription;
            }

            /**
             * Sets the value of the provisioningCodeDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProvisioningCodeDescription(String value) {
                this.provisioningCodeDescription = value;
            }

            /**
             * Gets the value of the customField property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the customField property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCustomField().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ProvisionableOrderCompleted.ItemList.Item.CustomField }
             * 
             * 
             */
            public List<ProvisionableOrderCompleted.ItemList.Item.CustomField> getCustomField() {
                if (customField == null) {
                    customField = new ArrayList<ProvisionableOrderCompleted.ItemList.Item.CustomField>();
                }
                return this.customField;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element ref="{}Value"/>
             *       &lt;/sequence>
             *       &lt;attribute name="Index" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "identifier",
                "name",
                "value"
            })
            public static class CustomField {

                @XmlElement(name = "Identifier", required = true)
                protected String identifier;
                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "Value", required = true)
                protected String value;
                @XmlAttribute(name = "Index", required = true)
                protected BigInteger index;

                /**
                 * Gets the value of the identifier property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIdentifier() {
                    return identifier;
                }

                /**
                 * Sets the value of the identifier property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIdentifier(String value) {
                    this.identifier = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the index property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getIndex() {
                    return index;
                }

                /**
                 * Sets the value of the index property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setIndex(BigInteger value) {
                    this.index = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}StartTelephoneNumberId"/>
             *         &lt;element ref="{}EndTelephoneNumberId"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "startTelephoneNumberId",
                "endTelephoneNumberId"
            })
            public static class TelephoneNumberBlock {

                @XmlElement(name = "StartTelephoneNumberId", required = true)
                protected String startTelephoneNumberId;
                @XmlElement(name = "EndTelephoneNumberId", required = true)
                protected String endTelephoneNumberId;

                /**
                 * Gets the value of the startTelephoneNumberId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStartTelephoneNumberId() {
                    return startTelephoneNumberId;
                }

                /**
                 * Sets the value of the startTelephoneNumberId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStartTelephoneNumberId(String value) {
                    this.startTelephoneNumberId = value;
                }

                /**
                 * Gets the value of the endTelephoneNumberId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEndTelephoneNumberId() {
                    return endTelephoneNumberId;
                }

                /**
                 * Sets the value of the endTelephoneNumberId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEndTelephoneNumberId(String value) {
                    this.endTelephoneNumberId = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}LocationId"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "locationId"
    })
    public static class Location {

        @XmlElement(name = "LocationId", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger locationId;

        /**
         * Gets the value of the locationId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLocationId() {
            return locationId;
        }

        /**
         * Sets the value of the locationId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLocationId(BigInteger value) {
            this.locationId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}OrderId"/>
     *         &lt;element ref="{}Class"/>
     *         &lt;element ref="{}Status"/>
     *         &lt;element ref="{}Version"/>
     *         &lt;element ref="{}DueDate" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderId",
        "clazz",
        "status",
        "version",
        "dueDate"
    })
    public static class Order {

        @XmlElement(name = "OrderId", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger orderId;
        @XmlElement(name = "Class", required = true)
        protected String clazz;
        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "Version", required = true)
        protected String version;
        @XmlElement(name = "DueDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dueDate;

        /**
         * Gets the value of the orderId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOrderId() {
            return orderId;
        }

        /**
         * Sets the value of the orderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOrderId(BigInteger value) {
            this.orderId = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the dueDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDueDate() {
            return dueDate;
        }

        /**
         * Sets the value of the dueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDueDate(XMLGregorianCalendar value) {
            this.dueDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TelephoneNumberBlock" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}StartTelephoneNumberId"/>
     *                   &lt;element ref="{}EndTelephoneNumberId"/>
     *                   &lt;element ref="{}Native"/>
     *                   &lt;element ref="{}PortedType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "telephoneNumberBlock"
    })
    public static class TelephoneNumberBlockList {

        @XmlElement(name = "TelephoneNumberBlock", required = true)
        protected List<ProvisionableOrderCompleted.TelephoneNumberBlockList.TelephoneNumberBlock> telephoneNumberBlock;

        /**
         * Gets the value of the telephoneNumberBlock property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the telephoneNumberBlock property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTelephoneNumberBlock().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProvisionableOrderCompleted.TelephoneNumberBlockList.TelephoneNumberBlock }
         * 
         * 
         */
        public List<ProvisionableOrderCompleted.TelephoneNumberBlockList.TelephoneNumberBlock> getTelephoneNumberBlock() {
            if (telephoneNumberBlock == null) {
                telephoneNumberBlock = new ArrayList<ProvisionableOrderCompleted.TelephoneNumberBlockList.TelephoneNumberBlock>();
            }
            return this.telephoneNumberBlock;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}StartTelephoneNumberId"/>
         *         &lt;element ref="{}EndTelephoneNumberId"/>
         *         &lt;element ref="{}Native"/>
         *         &lt;element ref="{}PortedType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "startTelephoneNumberId",
            "endTelephoneNumberId",
            "_native",
            "portedType"
        })
        public static class TelephoneNumberBlock {

            @XmlElement(name = "StartTelephoneNumberId", required = true)
            protected String startTelephoneNumberId;
            @XmlElement(name = "EndTelephoneNumberId", required = true)
            protected String endTelephoneNumberId;
            @XmlElement(name = "Native", required = true)
            protected String _native;
            @XmlElement(name = "PortedType", required = true)
            protected String portedType;

            /**
             * Gets the value of the startTelephoneNumberId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStartTelephoneNumberId() {
                return startTelephoneNumberId;
            }

            /**
             * Sets the value of the startTelephoneNumberId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStartTelephoneNumberId(String value) {
                this.startTelephoneNumberId = value;
            }

            /**
             * Gets the value of the endTelephoneNumberId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndTelephoneNumberId() {
                return endTelephoneNumberId;
            }

            /**
             * Sets the value of the endTelephoneNumberId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndTelephoneNumberId(String value) {
                this.endTelephoneNumberId = value;
            }

            /**
             * Gets the value of the native property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNative() {
                return _native;
            }

            /**
             * Sets the value of the native property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNative(String value) {
                this._native = value;
            }

            /**
             * Gets the value of the portedType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPortedType() {
                return portedType;
            }

            /**
             * Sets the value of the portedType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPortedType(String value) {
                this.portedType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TelephoneNumber" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}TelephoneNumberId"/>
     *                   &lt;element ref="{}Native"/>
     *                   &lt;element ref="{}PortedType"/>
     *                   &lt;element ref="{}Switch" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "telephoneNumber"
    })
    public static class TelephoneNumberList {

        @XmlElement(name = "TelephoneNumber", required = true)
        protected List<ProvisionableOrderCompleted.TelephoneNumberList.TelephoneNumber> telephoneNumber;

        /**
         * Gets the value of the telephoneNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the telephoneNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTelephoneNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProvisionableOrderCompleted.TelephoneNumberList.TelephoneNumber }
         * 
         * 
         */
        public List<ProvisionableOrderCompleted.TelephoneNumberList.TelephoneNumber> getTelephoneNumber() {
            if (telephoneNumber == null) {
                telephoneNumber = new ArrayList<ProvisionableOrderCompleted.TelephoneNumberList.TelephoneNumber>();
            }
            return this.telephoneNumber;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}TelephoneNumberId"/>
         *         &lt;element ref="{}Native"/>
         *         &lt;element ref="{}PortedType"/>
         *         &lt;element ref="{}Switch" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "telephoneNumberId",
            "_native",
            "portedType",
            "_switch"
        })
        public static class TelephoneNumber {

            @XmlElement(name = "TelephoneNumberId", required = true)
            protected String telephoneNumberId;
            @XmlElement(name = "Native", required = true)
            protected String _native;
            @XmlElement(name = "PortedType", required = true)
            protected String portedType;
            @XmlElement(name = "Switch")
            protected String _switch;

            /**
             * Gets the value of the telephoneNumberId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTelephoneNumberId() {
                return telephoneNumberId;
            }

            /**
             * Sets the value of the telephoneNumberId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTelephoneNumberId(String value) {
                this.telephoneNumberId = value;
            }

            /**
             * Gets the value of the native property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNative() {
                return _native;
            }

            /**
             * Sets the value of the native property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNative(String value) {
                this._native = value;
            }

            /**
             * Gets the value of the portedType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPortedType() {
                return portedType;
            }

            /**
             * Sets the value of the portedType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPortedType(String value) {
                this.portedType = value;
            }

            /**
             * Gets the value of the switch property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSwitch() {
                return _switch;
            }

            /**
             * Sets the value of the switch property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSwitch(String value) {
                this._switch = value;
            }

        }

    }

}
