//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.02 at 05:47:07 PM MST 
//


package com.hsphoenix.csg.sodi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hsdEmail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hsdEmail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Primary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}Provisionable"/>
 *         &lt;element ref="{}Solicitation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hsdEmail", propOrder = {
    "address",
    "primary",
    "provisionable",
    "solicitation"
})
public class HsdEmail {

    @XmlElement(name = "Address", required = true)
    protected String address;
    @XmlElement(name = "Primary", required = true)
    protected String primary;
    @XmlElement(name = "Provisionable", required = true)
    protected String provisionable;
    @XmlElement(name = "Solicitation", required = true)
    protected String solicitation;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimary(String value) {
        this.primary = value;
    }

    /**
     * Gets the value of the provisionable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvisionable() {
        return provisionable;
    }

    /**
     * Sets the value of the provisionable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvisionable(String value) {
        this.provisionable = value;
    }

    /**
     * Gets the value of the solicitation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolicitation() {
        return solicitation;
    }

    /**
     * Sets the value of the solicitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolicitation(String value) {
        this.solicitation = value;
    }

}
