//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.02 at 05:47:07 PM MST 
//


package com.hsphoenix.csg.sodi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for identificationF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identificationF">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TaxIdentifier"/>
 *         &lt;element ref="{}TaxType"/>
 *         &lt;element ref="{}BirthDate" minOccurs="0"/>
 *         &lt;element ref="{}DriversLicenseNumber" minOccurs="0"/>
 *         &lt;element ref="{}DriversLicenseState" minOccurs="0"/>
 *         &lt;element name="Alternate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Identifier"/>
 *                   &lt;element ref="{}Type"/>
 *                   &lt;element ref="{}TypeDescription"/>
 *                   &lt;element name="IssuerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IssuerCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identificationF", propOrder = {
    "taxIdentifier",
    "taxType",
    "birthDate",
    "driversLicenseNumber",
    "driversLicenseState",
    "alternate"
})
public class IdentificationF {

    @XmlElement(name = "TaxIdentifier", required = true)
    protected String taxIdentifier;
    @XmlElement(name = "TaxType", required = true)
    protected String taxType;
    @XmlElement(name = "BirthDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "DriversLicenseNumber")
    protected String driversLicenseNumber;
    @XmlElement(name = "DriversLicenseState")
    protected String driversLicenseState;
    @XmlElement(name = "Alternate")
    protected IdentificationF.Alternate alternate;

    /**
     * Gets the value of the taxIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIdentifier() {
        return taxIdentifier;
    }

    /**
     * Sets the value of the taxIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIdentifier(String value) {
        this.taxIdentifier = value;
    }

    /**
     * Gets the value of the taxType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxType() {
        return taxType;
    }

    /**
     * Sets the value of the taxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxType(String value) {
        this.taxType = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the driversLicenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriversLicenseNumber() {
        return driversLicenseNumber;
    }

    /**
     * Sets the value of the driversLicenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriversLicenseNumber(String value) {
        this.driversLicenseNumber = value;
    }

    /**
     * Gets the value of the driversLicenseState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriversLicenseState() {
        return driversLicenseState;
    }

    /**
     * Sets the value of the driversLicenseState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriversLicenseState(String value) {
        this.driversLicenseState = value;
    }

    /**
     * Gets the value of the alternate property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationF.Alternate }
     *     
     */
    public IdentificationF.Alternate getAlternate() {
        return alternate;
    }

    /**
     * Sets the value of the alternate property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationF.Alternate }
     *     
     */
    public void setAlternate(IdentificationF.Alternate value) {
        this.alternate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Identifier"/>
     *         &lt;element ref="{}Type"/>
     *         &lt;element ref="{}TypeDescription"/>
     *         &lt;element name="IssuerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IssuerCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identifier",
        "type",
        "typeDescription",
        "issuerCode",
        "issuerCodeDescription"
    })
    public static class Alternate {

        @XmlElement(name = "Identifier", required = true)
        protected String identifier;
        @XmlElement(name = "Type", required = true)
        protected String type;
        @XmlElement(name = "TypeDescription", required = true)
        protected String typeDescription;
        @XmlElement(name = "IssuerCode", required = true)
        protected String issuerCode;
        @XmlElement(name = "IssuerCodeDescription", required = true)
        protected String issuerCodeDescription;

        /**
         * Gets the value of the identifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifier(String value) {
            this.identifier = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the typeDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeDescription() {
            return typeDescription;
        }

        /**
         * Sets the value of the typeDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeDescription(String value) {
            this.typeDescription = value;
        }

        /**
         * Gets the value of the issuerCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIssuerCode() {
            return issuerCode;
        }

        /**
         * Sets the value of the issuerCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIssuerCode(String value) {
            this.issuerCode = value;
        }

        /**
         * Gets the value of the issuerCodeDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIssuerCodeDescription() {
            return issuerCodeDescription;
        }

        /**
         * Sets the value of the issuerCodeDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIssuerCodeDescription(String value) {
            this.issuerCodeDescription = value;
        }

    }

}
