//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.02 at 05:47:07 PM MST 
//


package com.hsphoenix.csg.sodi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parsedAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parsedAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Line1"/>
 *         &lt;element ref="{}Line2" minOccurs="0"/>
 *         &lt;element ref="{}City"/>
 *         &lt;element ref="{}State"/>
 *         &lt;element ref="{}PostalCode"/>
 *         &lt;element ref="{}Status"/>
 *         &lt;element ref="{}Message" minOccurs="0"/>
 *         &lt;element name="Parsed" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}HouseNumber" minOccurs="0"/>
 *                   &lt;element ref="{}HouseNumberSuffix" minOccurs="0"/>
 *                   &lt;element ref="{}PrefixDirectional" minOccurs="0"/>
 *                   &lt;element ref="{}Street" minOccurs="0"/>
 *                   &lt;element ref="{}StreetSuffix" minOccurs="0"/>
 *                   &lt;element ref="{}PostDirectional" minOccurs="0"/>
 *                   &lt;element ref="{}UnitDesignator1" minOccurs="0"/>
 *                   &lt;element ref="{}UnitValue1" minOccurs="0"/>
 *                   &lt;element ref="{}UnitDesignator2" minOccurs="0"/>
 *                   &lt;element ref="{}UnitValue2" minOccurs="0"/>
 *                   &lt;element ref="{}UnitDesignator3" minOccurs="0"/>
 *                   &lt;element ref="{}UnitValue3" minOccurs="0"/>
 *                   &lt;element ref="{}UnitDesignator4" minOccurs="0"/>
 *                   &lt;element ref="{}UnitValue4" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parsedAddress", propOrder = {
    "line1",
    "line2",
    "city",
    "state",
    "postalCode",
    "status",
    "message",
    "parsed"
})
public class ParsedAddress {

    @XmlElement(name = "Line1", required = true)
    protected String line1;
    @XmlElement(name = "Line2")
    protected String line2;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "PostalCode", required = true)
    protected String postalCode;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "Message")
    protected String message;
    @XmlElement(name = "Parsed")
    protected ParsedAddress.Parsed parsed;

    /**
     * Gets the value of the line1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine1() {
        return line1;
    }

    /**
     * Sets the value of the line1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine1(String value) {
        this.line1 = value;
    }

    /**
     * Gets the value of the line2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine2() {
        return line2;
    }

    /**
     * Sets the value of the line2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine2(String value) {
        this.line2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the parsed property.
     * 
     * @return
     *     possible object is
     *     {@link ParsedAddress.Parsed }
     *     
     */
    public ParsedAddress.Parsed getParsed() {
        return parsed;
    }

    /**
     * Sets the value of the parsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParsedAddress.Parsed }
     *     
     */
    public void setParsed(ParsedAddress.Parsed value) {
        this.parsed = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}HouseNumber" minOccurs="0"/>
     *         &lt;element ref="{}HouseNumberSuffix" minOccurs="0"/>
     *         &lt;element ref="{}PrefixDirectional" minOccurs="0"/>
     *         &lt;element ref="{}Street" minOccurs="0"/>
     *         &lt;element ref="{}StreetSuffix" minOccurs="0"/>
     *         &lt;element ref="{}PostDirectional" minOccurs="0"/>
     *         &lt;element ref="{}UnitDesignator1" minOccurs="0"/>
     *         &lt;element ref="{}UnitValue1" minOccurs="0"/>
     *         &lt;element ref="{}UnitDesignator2" minOccurs="0"/>
     *         &lt;element ref="{}UnitValue2" minOccurs="0"/>
     *         &lt;element ref="{}UnitDesignator3" minOccurs="0"/>
     *         &lt;element ref="{}UnitValue3" minOccurs="0"/>
     *         &lt;element ref="{}UnitDesignator4" minOccurs="0"/>
     *         &lt;element ref="{}UnitValue4" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "houseNumber",
        "houseNumberSuffix",
        "prefixDirectional",
        "street",
        "streetSuffix",
        "postDirectional",
        "unitDesignator1",
        "unitValue1",
        "unitDesignator2",
        "unitValue2",
        "unitDesignator3",
        "unitValue3",
        "unitDesignator4",
        "unitValue4"
    })
    public static class Parsed {

        @XmlElement(name = "HouseNumber")
        protected String houseNumber;
        @XmlElement(name = "HouseNumberSuffix")
        protected String houseNumberSuffix;
        @XmlElement(name = "PrefixDirectional")
        protected String prefixDirectional;
        @XmlElement(name = "Street")
        protected String street;
        @XmlElement(name = "StreetSuffix")
        protected String streetSuffix;
        @XmlElement(name = "PostDirectional")
        protected String postDirectional;
        @XmlElement(name = "UnitDesignator1")
        protected String unitDesignator1;
        @XmlElement(name = "UnitValue1")
        protected String unitValue1;
        @XmlElement(name = "UnitDesignator2")
        protected String unitDesignator2;
        @XmlElement(name = "UnitValue2")
        protected String unitValue2;
        @XmlElement(name = "UnitDesignator3")
        protected String unitDesignator3;
        @XmlElement(name = "UnitValue3")
        protected String unitValue3;
        @XmlElement(name = "UnitDesignator4")
        protected String unitDesignator4;
        @XmlElement(name = "UnitValue4")
        protected String unitValue4;

        /**
         * Gets the value of the houseNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHouseNumber() {
            return houseNumber;
        }

        /**
         * Sets the value of the houseNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHouseNumber(String value) {
            this.houseNumber = value;
        }

        /**
         * Gets the value of the houseNumberSuffix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHouseNumberSuffix() {
            return houseNumberSuffix;
        }

        /**
         * Sets the value of the houseNumberSuffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHouseNumberSuffix(String value) {
            this.houseNumberSuffix = value;
        }

        /**
         * Gets the value of the prefixDirectional property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrefixDirectional() {
            return prefixDirectional;
        }

        /**
         * Sets the value of the prefixDirectional property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrefixDirectional(String value) {
            this.prefixDirectional = value;
        }

        /**
         * Gets the value of the street property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStreet() {
            return street;
        }

        /**
         * Sets the value of the street property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStreet(String value) {
            this.street = value;
        }

        /**
         * Gets the value of the streetSuffix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStreetSuffix() {
            return streetSuffix;
        }

        /**
         * Sets the value of the streetSuffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStreetSuffix(String value) {
            this.streetSuffix = value;
        }

        /**
         * Gets the value of the postDirectional property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostDirectional() {
            return postDirectional;
        }

        /**
         * Sets the value of the postDirectional property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostDirectional(String value) {
            this.postDirectional = value;
        }

        /**
         * Gets the value of the unitDesignator1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitDesignator1() {
            return unitDesignator1;
        }

        /**
         * Sets the value of the unitDesignator1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitDesignator1(String value) {
            this.unitDesignator1 = value;
        }

        /**
         * Gets the value of the unitValue1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitValue1() {
            return unitValue1;
        }

        /**
         * Sets the value of the unitValue1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitValue1(String value) {
            this.unitValue1 = value;
        }

        /**
         * Gets the value of the unitDesignator2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitDesignator2() {
            return unitDesignator2;
        }

        /**
         * Sets the value of the unitDesignator2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitDesignator2(String value) {
            this.unitDesignator2 = value;
        }

        /**
         * Gets the value of the unitValue2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitValue2() {
            return unitValue2;
        }

        /**
         * Sets the value of the unitValue2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitValue2(String value) {
            this.unitValue2 = value;
        }

        /**
         * Gets the value of the unitDesignator3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitDesignator3() {
            return unitDesignator3;
        }

        /**
         * Sets the value of the unitDesignator3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitDesignator3(String value) {
            this.unitDesignator3 = value;
        }

        /**
         * Gets the value of the unitValue3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitValue3() {
            return unitValue3;
        }

        /**
         * Sets the value of the unitValue3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitValue3(String value) {
            this.unitValue3 = value;
        }

        /**
         * Gets the value of the unitDesignator4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitDesignator4() {
            return unitDesignator4;
        }

        /**
         * Sets the value of the unitDesignator4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitDesignator4(String value) {
            this.unitDesignator4 = value;
        }

        /**
         * Gets the value of the unitValue4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitValue4() {
            return unitValue4;
        }

        /**
         * Sets the value of the unitValue4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitValue4(String value) {
            this.unitValue4 = value;
        }

    }

}
