//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.02 at 05:47:07 PM MST 
//


package com.hsphoenix.csg.sodi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for privacyA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="privacyA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Disclose" minOccurs="0"/>
 *         &lt;element ref="{}DisclosureParty" minOccurs="0"/>
 *         &lt;element ref="{}DisclosurePartyDescription" minOccurs="0"/>
 *         &lt;element ref="{}ContactMethod" minOccurs="0"/>
 *         &lt;element ref="{}ContactMethodDescription" minOccurs="0"/>
 *         &lt;element name="Audit3" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LastUpdate" type="{}auditD"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "privacyA", propOrder = {
    "disclose",
    "disclosureParty",
    "disclosurePartyDescription",
    "contactMethod",
    "contactMethodDescription",
    "audit3"
})
public class PrivacyA {

    @XmlElement(name = "Disclose")
    protected String disclose;
    @XmlElement(name = "DisclosureParty")
    protected String disclosureParty;
    @XmlElement(name = "DisclosurePartyDescription")
    protected String disclosurePartyDescription;
    @XmlElement(name = "ContactMethod")
    protected String contactMethod;
    @XmlElement(name = "ContactMethodDescription")
    protected String contactMethodDescription;
    @XmlElement(name = "Audit3")
    protected PrivacyA.Audit3 audit3;

    /**
     * Gets the value of the disclose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclose() {
        return disclose;
    }

    /**
     * Sets the value of the disclose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclose(String value) {
        this.disclose = value;
    }

    /**
     * Gets the value of the disclosureParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclosureParty() {
        return disclosureParty;
    }

    /**
     * Sets the value of the disclosureParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclosureParty(String value) {
        this.disclosureParty = value;
    }

    /**
     * Gets the value of the disclosurePartyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclosurePartyDescription() {
        return disclosurePartyDescription;
    }

    /**
     * Sets the value of the disclosurePartyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclosurePartyDescription(String value) {
        this.disclosurePartyDescription = value;
    }

    /**
     * Gets the value of the contactMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactMethod() {
        return contactMethod;
    }

    /**
     * Sets the value of the contactMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactMethod(String value) {
        this.contactMethod = value;
    }

    /**
     * Gets the value of the contactMethodDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactMethodDescription() {
        return contactMethodDescription;
    }

    /**
     * Sets the value of the contactMethodDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactMethodDescription(String value) {
        this.contactMethodDescription = value;
    }

    /**
     * Gets the value of the audit3 property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyA.Audit3 }
     *     
     */
    public PrivacyA.Audit3 getAudit3() {
        return audit3;
    }

    /**
     * Sets the value of the audit3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyA.Audit3 }
     *     
     */
    public void setAudit3(PrivacyA.Audit3 value) {
        this.audit3 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LastUpdate" type="{}auditD"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lastUpdate"
    })
    public static class Audit3 {

        @XmlElement(name = "LastUpdate", required = true)
        protected AuditD lastUpdate;

        /**
         * Gets the value of the lastUpdate property.
         * 
         * @return
         *     possible object is
         *     {@link AuditD }
         *     
         */
        public AuditD getLastUpdate() {
            return lastUpdate;
        }

        /**
         * Sets the value of the lastUpdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link AuditD }
         *     
         */
        public void setLastUpdate(AuditD value) {
            this.lastUpdate = value;
        }

    }

}
