//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.02 at 05:47:07 PM MST 
//


package com.hsphoenix.csg.sodi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for usageSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="usageSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Type"/>
 *         &lt;element ref="{}SubType" minOccurs="0"/>
 *         &lt;element ref="{}UserName"/>
 *         &lt;element name="Billing">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}CalculationMethod"/>
 *                   &lt;element ref="{}UnitOfMeasure"/>
 *                   &lt;element ref="{}FromDate"/>
 *                   &lt;element ref="{}ThruDate"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Units">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}InitialAllotted"/>
 *                   &lt;element ref="{}TotalAllotted"/>
 *                   &lt;element ref="{}TotalUsed"/>
 *                   &lt;element ref="{}TotalUnused"/>
 *                   &lt;element ref="{}EndCycleIndicator"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}Date"/>
 *         &lt;element ref="{}Time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "usageSummary", propOrder = {
    "type",
    "subType",
    "userName",
    "billing",
    "units",
    "date",
    "time"
})
public class UsageSummary {

    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "SubType")
    protected String subType;
    @XmlElement(name = "UserName", required = true)
    protected String userName;
    @XmlElement(name = "Billing", required = true)
    protected UsageSummary.Billing billing;
    @XmlElement(name = "Units", required = true)
    protected UsageSummary.Units units;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "Time", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubType() {
        return subType;
    }

    /**
     * Sets the value of the subType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubType(String value) {
        this.subType = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the billing property.
     * 
     * @return
     *     possible object is
     *     {@link UsageSummary.Billing }
     *     
     */
    public UsageSummary.Billing getBilling() {
        return billing;
    }

    /**
     * Sets the value of the billing property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageSummary.Billing }
     *     
     */
    public void setBilling(UsageSummary.Billing value) {
        this.billing = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link UsageSummary.Units }
     *     
     */
    public UsageSummary.Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageSummary.Units }
     *     
     */
    public void setUnits(UsageSummary.Units value) {
        this.units = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}CalculationMethod"/>
     *         &lt;element ref="{}UnitOfMeasure"/>
     *         &lt;element ref="{}FromDate"/>
     *         &lt;element ref="{}ThruDate"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "calculationMethod",
        "unitOfMeasure",
        "fromDate",
        "thruDate"
    })
    public static class Billing {

        @XmlElement(name = "CalculationMethod", required = true)
        protected String calculationMethod;
        @XmlElement(name = "UnitOfMeasure", required = true)
        protected String unitOfMeasure;
        @XmlElement(name = "FromDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fromDate;
        @XmlElement(name = "ThruDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar thruDate;

        /**
         * Gets the value of the calculationMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCalculationMethod() {
            return calculationMethod;
        }

        /**
         * Sets the value of the calculationMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCalculationMethod(String value) {
            this.calculationMethod = value;
        }

        /**
         * Gets the value of the unitOfMeasure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitOfMeasure() {
            return unitOfMeasure;
        }

        /**
         * Sets the value of the unitOfMeasure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitOfMeasure(String value) {
            this.unitOfMeasure = value;
        }

        /**
         * Gets the value of the fromDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFromDate() {
            return fromDate;
        }

        /**
         * Sets the value of the fromDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFromDate(XMLGregorianCalendar value) {
            this.fromDate = value;
        }

        /**
         * Gets the value of the thruDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getThruDate() {
            return thruDate;
        }

        /**
         * Sets the value of the thruDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setThruDate(XMLGregorianCalendar value) {
            this.thruDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}InitialAllotted"/>
     *         &lt;element ref="{}TotalAllotted"/>
     *         &lt;element ref="{}TotalUsed"/>
     *         &lt;element ref="{}TotalUnused"/>
     *         &lt;element ref="{}EndCycleIndicator"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initialAllotted",
        "totalAllotted",
        "totalUsed",
        "totalUnused",
        "endCycleIndicator"
    })
    public static class Units {

        @XmlElement(name = "InitialAllotted", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger initialAllotted;
        @XmlElement(name = "TotalAllotted", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger totalAllotted;
        @XmlElement(name = "TotalUsed", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger totalUsed;
        @XmlElement(name = "TotalUnused", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger totalUnused;
        @XmlElement(name = "EndCycleIndicator", required = true)
        protected String endCycleIndicator;

        /**
         * Gets the value of the initialAllotted property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getInitialAllotted() {
            return initialAllotted;
        }

        /**
         * Sets the value of the initialAllotted property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setInitialAllotted(BigInteger value) {
            this.initialAllotted = value;
        }

        /**
         * Gets the value of the totalAllotted property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalAllotted() {
            return totalAllotted;
        }

        /**
         * Sets the value of the totalAllotted property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalAllotted(BigInteger value) {
            this.totalAllotted = value;
        }

        /**
         * Gets the value of the totalUsed property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalUsed() {
            return totalUsed;
        }

        /**
         * Sets the value of the totalUsed property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalUsed(BigInteger value) {
            this.totalUsed = value;
        }

        /**
         * Gets the value of the totalUnused property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalUnused() {
            return totalUnused;
        }

        /**
         * Sets the value of the totalUnused property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalUnused(BigInteger value) {
            this.totalUnused = value;
        }

        /**
         * Gets the value of the endCycleIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndCycleIndicator() {
            return endCycleIndicator;
        }

        /**
         * Sets the value of the endCycleIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndCycleIndicator(String value) {
            this.endCycleIndicator = value;
        }

    }

}
