//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.02 at 05:47:07 PM MST 
//


package com.hsphoenix.csg.sodi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for videoTypeA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="videoTypeA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}HostIdentifier" minOccurs="0"/>
 *         &lt;element name="AssociatedEquipment" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}EquipmentId"/>
 *                   &lt;element ref="{}SerialNumber"/>
 *                   &lt;element ref="{}Type"/>
 *                   &lt;element ref="{}TypeDescription"/>
 *                   &lt;element ref="{}ComponentCode"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "videoTypeA", propOrder = {
    "hostIdentifier",
    "associatedEquipment"
})
public class VideoTypeA {

    @XmlElement(name = "HostIdentifier")
    protected String hostIdentifier;
    @XmlElement(name = "AssociatedEquipment")
    protected VideoTypeA.AssociatedEquipment associatedEquipment;

    /**
     * Gets the value of the hostIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostIdentifier() {
        return hostIdentifier;
    }

    /**
     * Sets the value of the hostIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostIdentifier(String value) {
        this.hostIdentifier = value;
    }

    /**
     * Gets the value of the associatedEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link VideoTypeA.AssociatedEquipment }
     *     
     */
    public VideoTypeA.AssociatedEquipment getAssociatedEquipment() {
        return associatedEquipment;
    }

    /**
     * Sets the value of the associatedEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoTypeA.AssociatedEquipment }
     *     
     */
    public void setAssociatedEquipment(VideoTypeA.AssociatedEquipment value) {
        this.associatedEquipment = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}EquipmentId"/>
     *         &lt;element ref="{}SerialNumber"/>
     *         &lt;element ref="{}Type"/>
     *         &lt;element ref="{}TypeDescription"/>
     *         &lt;element ref="{}ComponentCode"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "equipmentId",
        "serialNumber",
        "type",
        "typeDescription",
        "componentCode"
    })
    public static class AssociatedEquipment {

        @XmlElement(name = "EquipmentId", required = true)
        protected String equipmentId;
        @XmlElement(name = "SerialNumber", required = true)
        protected String serialNumber;
        @XmlElement(name = "Type", required = true)
        protected String type;
        @XmlElement(name = "TypeDescription", required = true)
        protected String typeDescription;
        @XmlElement(name = "ComponentCode", required = true)
        protected String componentCode;

        /**
         * Gets the value of the equipmentId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEquipmentId() {
            return equipmentId;
        }

        /**
         * Sets the value of the equipmentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEquipmentId(String value) {
            this.equipmentId = value;
        }

        /**
         * Gets the value of the serialNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSerialNumber() {
            return serialNumber;
        }

        /**
         * Sets the value of the serialNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSerialNumber(String value) {
            this.serialNumber = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the typeDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeDescription() {
            return typeDescription;
        }

        /**
         * Sets the value of the typeDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeDescription(String value) {
            this.typeDescription = value;
        }

        /**
         * Gets the value of the componentCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComponentCode() {
            return componentCode;
        }

        /**
         * Sets the value of the componentCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComponentCode(String value) {
            this.componentCode = value;
        }

    }

}
