//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.02 at 05:47:07 PM MST 
//


package com.hsphoenix.csg.sodi.update.voice;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.hsphoenix.csg.sodi.MsagA;
import com.hsphoenix.csg.sodi.ParsedAddressUpdate;
import com.hsphoenix.csg.sodi.TextA;
import com.hsphoenix.csg.sodi.VendorKey;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Location" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}LocationId"/>
 *                   &lt;element name="Address" type="{}parsedAddressUpdate" minOccurs="0"/>
 *                   &lt;element name="MSAG" type="{}msagA" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Order">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}OrderId"/>
 *                   &lt;element ref="{}Status" minOccurs="0"/>
 *                   &lt;element ref="{}SubStatus" minOccurs="0"/>
 *                   &lt;element ref="{}Version"/>
 *                   &lt;element name="Comment" type="{}textA" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{}Exception" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ItemList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Item" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}ServiceIdentifier"/>
 *                             &lt;element ref="{}TelephoneNumberId" minOccurs="0"/>
 *                             &lt;element ref="{}WorkPlanItemIdentifier"/>
 *                             &lt;element ref="{}Status"/>
 *                             &lt;element ref="{}CompletionDate" minOccurs="0"/>
 *                             &lt;element ref="{}CompletionTime" minOccurs="0"/>
 *                             &lt;element name="Comment" type="{}textA" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element ref="{}Exception" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Vendor" type="{}vendorKey" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "location",
    "order",
    "itemList",
    "vendor"
})
@XmlRootElement(name = "UpdateVoiceOrder")
public class UpdateVoiceOrder {

    @XmlElement(name = "Location")
    protected UpdateVoiceOrder.Location location;
    @XmlElement(name = "Order", required = true)
    protected UpdateVoiceOrder.Order order;
    @XmlElement(name = "ItemList")
    protected UpdateVoiceOrder.ItemList itemList;
    @XmlElement(name = "Vendor")
    protected VendorKey vendor;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateVoiceOrder.Location }
     *     
     */
    public UpdateVoiceOrder.Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateVoiceOrder.Location }
     *     
     */
    public void setLocation(UpdateVoiceOrder.Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateVoiceOrder.Order }
     *     
     */
    public UpdateVoiceOrder.Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateVoiceOrder.Order }
     *     
     */
    public void setOrder(UpdateVoiceOrder.Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the itemList property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateVoiceOrder.ItemList }
     *     
     */
    public UpdateVoiceOrder.ItemList getItemList() {
        return itemList;
    }

    /**
     * Sets the value of the itemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateVoiceOrder.ItemList }
     *     
     */
    public void setItemList(UpdateVoiceOrder.ItemList value) {
        this.itemList = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link VendorKey }
     *     
     */
    public VendorKey getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorKey }
     *     
     */
    public void setVendor(VendorKey value) {
        this.vendor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Item" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}ServiceIdentifier"/>
     *                   &lt;element ref="{}TelephoneNumberId" minOccurs="0"/>
     *                   &lt;element ref="{}WorkPlanItemIdentifier"/>
     *                   &lt;element ref="{}Status"/>
     *                   &lt;element ref="{}CompletionDate" minOccurs="0"/>
     *                   &lt;element ref="{}CompletionTime" minOccurs="0"/>
     *                   &lt;element name="Comment" type="{}textA" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element ref="{}Exception" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class ItemList {

        @XmlElement(name = "Item", required = true)
        protected List<UpdateVoiceOrder.ItemList.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UpdateVoiceOrder.ItemList.Item }
         * 
         * 
         */
        public List<UpdateVoiceOrder.ItemList.Item> getItem() {
            if (item == null) {
                item = new ArrayList<UpdateVoiceOrder.ItemList.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}ServiceIdentifier"/>
         *         &lt;element ref="{}TelephoneNumberId" minOccurs="0"/>
         *         &lt;element ref="{}WorkPlanItemIdentifier"/>
         *         &lt;element ref="{}Status"/>
         *         &lt;element ref="{}CompletionDate" minOccurs="0"/>
         *         &lt;element ref="{}CompletionTime" minOccurs="0"/>
         *         &lt;element name="Comment" type="{}textA" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element ref="{}Exception" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "serviceIdentifier",
            "telephoneNumberId",
            "workPlanItemIdentifier",
            "status",
            "completionDate",
            "completionTime",
            "comment",
            "exception"
        })
        public static class Item {

            @XmlElement(name = "ServiceIdentifier", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger serviceIdentifier;
            @XmlElement(name = "TelephoneNumberId")
            protected String telephoneNumberId;
            @XmlElement(name = "WorkPlanItemIdentifier", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger workPlanItemIdentifier;
            @XmlElement(name = "Status", required = true)
            protected String status;
            @XmlElement(name = "CompletionDate")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar completionDate;
            @XmlElement(name = "CompletionTime")
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar completionTime;
            @XmlElement(name = "Comment")
            protected List<TextA> comment;
            @XmlElement(name = "Exception")
            protected Exception exception;

            /**
             * Gets the value of the serviceIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getServiceIdentifier() {
                return serviceIdentifier;
            }

            /**
             * Sets the value of the serviceIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setServiceIdentifier(BigInteger value) {
                this.serviceIdentifier = value;
            }

            /**
             * Gets the value of the telephoneNumberId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTelephoneNumberId() {
                return telephoneNumberId;
            }

            /**
             * Sets the value of the telephoneNumberId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTelephoneNumberId(String value) {
                this.telephoneNumberId = value;
            }

            /**
             * Gets the value of the workPlanItemIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getWorkPlanItemIdentifier() {
                return workPlanItemIdentifier;
            }

            /**
             * Sets the value of the workPlanItemIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setWorkPlanItemIdentifier(BigInteger value) {
                this.workPlanItemIdentifier = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the completionDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCompletionDate() {
                return completionDate;
            }

            /**
             * Sets the value of the completionDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCompletionDate(XMLGregorianCalendar value) {
                this.completionDate = value;
            }

            /**
             * Gets the value of the completionTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCompletionTime() {
                return completionTime;
            }

            /**
             * Sets the value of the completionTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCompletionTime(XMLGregorianCalendar value) {
                this.completionTime = value;
            }

            /**
             * Gets the value of the comment property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the comment property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getComment().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TextA }
             * 
             * 
             */
            public List<TextA> getComment() {
                if (comment == null) {
                    comment = new ArrayList<TextA>();
                }
                return this.comment;
            }

            /**
             * Gets the value of the exception property.
             * 
             * @return
             *     possible object is
             *     {@link Exception }
             *     
             */
            public Exception getException() {
                return exception;
            }

            /**
             * Sets the value of the exception property.
             * 
             * @param value
             *     allowed object is
             *     {@link Exception }
             *     
             */
            public void setException(Exception value) {
                this.exception = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}LocationId"/>
     *         &lt;element name="Address" type="{}parsedAddressUpdate" minOccurs="0"/>
     *         &lt;element name="MSAG" type="{}msagA" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "locationId",
        "address",
        "msag"
    })
    public static class Location {

        @XmlElement(name = "LocationId", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger locationId;
        @XmlElement(name = "Address")
        protected ParsedAddressUpdate address;
        @XmlElement(name = "MSAG")
        protected MsagA msag;

        /**
         * Gets the value of the locationId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLocationId() {
            return locationId;
        }

        /**
         * Sets the value of the locationId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLocationId(BigInteger value) {
            this.locationId = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link ParsedAddressUpdate }
         *     
         */
        public ParsedAddressUpdate getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParsedAddressUpdate }
         *     
         */
        public void setAddress(ParsedAddressUpdate value) {
            this.address = value;
        }

        /**
         * Gets the value of the msag property.
         * 
         * @return
         *     possible object is
         *     {@link MsagA }
         *     
         */
        public MsagA getMSAG() {
            return msag;
        }

        /**
         * Sets the value of the msag property.
         * 
         * @param value
         *     allowed object is
         *     {@link MsagA }
         *     
         */
        public void setMSAG(MsagA value) {
            this.msag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}OrderId"/>
     *         &lt;element ref="{}Status" minOccurs="0"/>
     *         &lt;element ref="{}SubStatus" minOccurs="0"/>
     *         &lt;element ref="{}Version"/>
     *         &lt;element name="Comment" type="{}textA" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{}Exception" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderId",
        "status",
        "subStatus",
        "version",
        "comment",
        "exception"
    })
    public static class Order {

        @XmlElement(name = "OrderId", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger orderId;
        @XmlElement(name = "Status")
        protected String status;
        @XmlElement(name = "SubStatus")
        protected String subStatus;
        @XmlElement(name = "Version", required = true)
        protected String version;
        @XmlElement(name = "Comment")
        protected List<TextA> comment;
        @XmlElement(name = "Exception")
        protected Exception exception;

        /**
         * Gets the value of the orderId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOrderId() {
            return orderId;
        }

        /**
         * Sets the value of the orderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOrderId(BigInteger value) {
            this.orderId = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the subStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubStatus() {
            return subStatus;
        }

        /**
         * Sets the value of the subStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubStatus(String value) {
            this.subStatus = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the comment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextA }
         * 
         * 
         */
        public List<TextA> getComment() {
            if (comment == null) {
                comment = new ArrayList<TextA>();
            }
            return this.comment;
        }

        /**
         * Gets the value of the exception property.
         * 
         * @return
         *     possible object is
         *     {@link Exception }
         *     
         */
        public Exception getException() {
            return exception;
        }

        /**
         * Sets the value of the exception property.
         * 
         * @param value
         *     allowed object is
         *     {@link Exception }
         *     
         */
        public void setException(Exception value) {
            this.exception = value;
        }

    }

}
